const ACHIEVEMENTS = ['participantStreak', 
                      'participantPoint', 
                      'firstPlace', 
                      'secondPlace', 
                      'thirdPlace', 
                      'bigChallenge', 
                      'smallChallenge', 
                      'shared', 
                      'noSS', 
                      'penalty'];

const REDEEMABLE_ITEMS = {
    item5500: { points: 5500, name: "Random SV Booster Box X 1" },
    item1300: { points: 1300, name: "Random SV Booster Bundle X 1" },
    item1000: { points: 1000, name: "Mystery Gift X 10" },
    item600: { points: 600, name: "Random SV Booster Pack X 3" },
    item400: { points: 400, name: "Discover Collectibles Playmat X 1" },
    item300: { points: 300, name: "Mystery Gift X 3" },
    item220: { points: 220, name: "Random SV Booster Pack X 1" },
    item100: { points: 100, name: "Mystery Gift X 1" },
    item20: { points: 20, name: "Bro Hug X 1" }
};

const PLAYERS = [
    "弱鸡",
    "四代火影",
    "你以为",
    "卡比兽",
    "沙奈朵",
    "咆𠱼之心",
    "我想要冰伊布ex！",
    "女の子の夢",
    "ダム",
    "닝닝",
    "!?",
    "30William",
    "4Shawn3",
    "Abamzdonat",
    "Abuyot",
    "AdamSoCool",
    "AdibAlexx",
    "afiqkay",
    "apple04",
    "Arnim",
    "Babal33",
    "Beepyenn",
    "Ben dover",
    "big boss",
    "BigdaddyMuz",
    "bigboss",
    "bingsu",
    "BlackJack",
    "BLITZ",
    "Bman",
    "Bolts95",
    "Bryan666",
    "bt",
    "buahkurma",
    "Cax_tcg",
    "ccxlol68",
    "Charizard JJ",
    "chibisan",
    "ck",
    "Claris",
    "Cokoroi",
    "COMS",
    "Dan_C",
    "Dank94",
    "DiamondIvan",
    "DLGF",
    "DraculeEX",
    "DY",
    "Eliot",
    "EmperorKizuna",
    "EntityZ",
    "Erina",
    "Euphoric",
    "eve",
    "expect_unexpec",
    "EXIA",
    "FastThrust",
    "Fiqdi94",
    "Flamingo",
    "Freewin88",
    "GengKay",
    "geminikid",
    "Ghost0910",
    "GiornoGiovarno",
    "GrandMaster H",
    "Gucci",
    "Haru",
    "Hean",
    "Hira",
    "Hobo",
    "Hongan",
    "hou",
    "How Shan",
    "Imhays",
    "Jäger",
    "Jay",
    "JcBluee",
    "Jcv",
    "Je Ketchum",
    "Jeffry",
    "Jhong",
    "jieeeee",
    "Jinnathannn",
    "Jkay",
    "Joe",
    "JoShua",
    "JoStream",
    "Juiceable1",
    "junhau2nd",
    "Kafka",
    "Kai",
    "Kaminrider",
    "Kate",
    "kekginsane",
    "Kowl09",
    "kuku",
    "LAYNE",
    "Le69",
    "Leoluxy",
    "Lootfee",
    "Lum Run",
    "Lucasyhc",
    "LuckyBoyy6",
    "Lwi",
    "matcan",
    "Maverick666",
    "MaveRick",
    "mch3w",
    "megapotato",
    "Michu",
    "MiEiKa<3",
    "Moses",
    "Mr Vege",
    "MrMal15",
    "MrManggis",
    "MrNobody",
    "MyzticJJ",
    "N",
    "Nerasid",
    "NeruJP",
    "Nexus",
    "NightKnight",
    "No pika",
    "NovaJJ",
    "Nullboi",
    "numbnuts96",
    "nutellacaster",
    "oOoish",
    "OiShi",
    "Omiki giggy",
    "onion",
    "Otak Kosong",
    "Paansem",
    "palskiee",
    "pekozii",
    "PhyRex",
    "PisangGoreng",
    "pookiem0n",
    "PoPing",
    "Potatoey",
    "Premages",
    "Proguy98",
    "punctual",
    "Pyzz",
    "Qiu Yue",
    "Random35",
    "red",
    "RedFissure",
    "RND35",
    "Sam",
    "Satoshi",
    "Scarecrow88",
    "Seanny",
    "Secret",
    "SMSG-B",
    "SOADeath",
    "SquirtleSax",
    "Starz.Aki",
    "Sumgor",
    "TakdeLaksa",
    "The Silencer",
    "Trainer_Blue",
    "TRUMP",
    "Uchiha.M",
    "UQwerts",
    "Wa.C",
    "wabafettt",
    "waikei",
    "Walalazz",
    "watashiwakunji",
    "Win",
    "Wk",
    "xBITWx",
    "xN3verminDx",
    "XenusG7",
    "YJong",
    "Yomamabijj",
    "Z TCG player",
    "Zoro",
    "Zulhusni98",
    "Zzzxzz",
    "m0neys",
    "ZX"
];